# =================================
# SERVICE CONFIGURATION
# =================================
server:
  port: 8081

# =================================
# EUREKA CLIENT
# =================================
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# =======================================
# Enables Spring Boot Actuator end points
# =======================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

# =======================================
# Database 
# =======================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_online_shop_customer_service?useLegacyDatetimeCode=false&serverTimezone=Africa/Douala&zeroDateTimeBehavior=convertToNull&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
  sql:
    init:
      platform: mysql
      mode: always
      encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev 